[project]
name = "config-migrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.12.4", "rich>=14.2.0", "typer>=0.20.0"]

[project.scripts]
migrator = "src.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
